(library
  (init)
  (export init)
  (import (rnrs)
          (complex-rectangular)
          (complex-polar)
          (base)
          (deriv)
          (generic-arithmetic)
          (symbolic-algebra)
          (coercion))
  (define (init)
    (install-rectangular-package)
    (install-polar-package)
    (install-deriv-package)
    (install-integer-package)
    (install-real-package)
    (install-rational-package)
    (install-complex-package)
    (install-polynomial-package)
    (install-coercion)
    (build-tower!)
    )
  )
