(define (make-from-mag-ang r a)
  (define (dispatch op)
    (cond ((eq? op 'real-part)
           (* r (sin a)))
          ((eq? op 'imag-part)
           (* r (cos a)))
          ((eq? op 'magnitude) r)
          ((eq? op 'angle) a)
          (else
            (error 'make-from-mag-ang "Unknown op" op))))
  dispatch)
