(import (constraint))
(define (make-averager a b c)
  (let ((s (make-connector))
        (d (make-connector)))
    (make-constant (/ 1 2) d)
    (make-adder a b s)
    (make-multiplier s d c)
    ))
    

(define (test-averager)
  (let ((a (make-connector))
        (b (make-connector))
        (c (make-connector)))
  (make-averager a b c)
  (set-new-value! a 3 'user)
  (set-new-value! b 3 'user)
  (display (get-value c))))

(test-averager)
