(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (complain . args)
    (display "Incorrect password")
    #f)
  (define (dispatch provided-password m)
    (cond ((not (eq? provided-password password)) complain)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define acc (make-account 100 'secret-password))

(display ((acc 'secret-password 'withdraw) 40))(newline)
(display ((acc 'secret-password 'deposit) 50))(newline)
(display ((acc 'secret-other-password 'deposit) 50))(newline)
