(define (complain . args)
  (display "Incorrect password")
  #f)
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)

  (define (dispatch provided-password m)
    (cond ((not (eq? provided-password password)) complain)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define (make-joint original-acc original-pwd joint-pwd)
  (define (dispatch provided-pwd m)
    (cond ((not (eq? provided-pwd joint-pwd))
           complain)
          (else (original-acc original-pwd m))))
  dispatch)

(define liwei (make-account 100 'listerine))
(define seckcoder (make-joint liwei 'listerine 'lenovo))
(display ((seckcoder 'lenovo 'withdraw) 20))(newline)
(display ((liwei 'listerine 'withdraw) 20))(newline)
(display ((seckcoder 'lenovo 'deposit) 50))(newline)
